version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: booking-schedule-postgres
    environment:
      POSTGRES_DB: booking_schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-schedule-network

  adminer:
    image: adminer
    container_name: booking-schedule-adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - booking-schedule-network

volumes:
  postgres_data:

networks:
  booking-schedule-network:
    driver: bridge
